version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-my-secret-pw}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-2i_book}
      MYSQL_USER: 2ibook
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-lemdp}
      MYSQL_TCP_PORT: 3307
      TZ: Europe/Paris
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: 2ibook:latest
    ports:
      - "8000:80"
    environment:
      name: "2ibook"
      DATABASE_URL: "mysql://2ibook:lemdp@database:3307/2i_book"

      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
   mysql-data:
###< doctrine/doctrine-bundle ###
