App\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [email]
        message: 'app.form.error.email.unique'
  properties:
    firstname:
      - Length:
          min: 3
          max: 20
          maxMessage: 'app.form.error.firstname.max_length'
          minMessage: 'app.form.error.firstname.min_length'
    lastname:
      - Length:
          min: 2
          max: 30
          maxMessage: 'app.form.error.lastname.max_length'
          minMessage: 'app.form.error.lastname.min_length'
    email:
      - Email:
          message: 'app.form.error.email.type'
    password:
      - Length:
          min: 8
          minMessage: 'app.form.error.password.min_length'
App\Entity\Address:
  properties:
    firstname:
      - Length:
          min: 3
          max: 30
          maxMessage: 'app.form.error.address.firstname.max_length'
          minMessage: 'app.form.error.address.firstname.min_length'
      - NotBlank:
          message: 'app.form.field.needed'
    lastname:
      - Length:
          min: 3
          max: 30
          maxMessage: 'app.form.error.address.lastname.max_length'
          minMessage: 'app.form.error.address.lastname.min_length'
      - NotBlank:
          message: 'app.form.field.needed'
    street:
      - Length:
          min: 3
          max: 255
          maxMessage: 'app.form.error.address.street.max_length'
          minMessage: 'app.form.error.address.street.min_length'
      - NotBlank:
          message: 'app.form.field.needed'
    postalCode:
      - Length:
          min: 5
          max: 5
          maxMessage: 'app.form.error.address.postal_code'
          minMessage: 'app.form.error.address.postal_code'
    city:
      - Length:
          min: 3
          max: 255
          maxMessage: 'app.form.error.address.city.max_length'
          minMessage: 'app.form.error.address.city.min_length'
      - NotBlank:
          message: 'app.form.field.needed'
App\Entity\OrderItem:
  properties:
    ordered:
      - NotNull: ~
    variant:
      - NotNull: ~
    quantity:
      - NotNull: ~
    price:
      - NotNull: ~
    tax:
      - NotNull: ~
App\Entity\Tax:
  properties:
    name:
      - NotNull: ~
    amount:
      - NotNull: ~
App\Entity\Abstract\BaseVariant\BaseVariant:
  properties:
    stock:
      - NotNull: ~
    unitPrice:
      - NotNull: ~
    tax:
      - NotNull: ~
App\Entity\Abstract\BaseArticle\BaseArticle:
  properties:
    title:
      - NotNull: ~
    resume:
      - NotNull: ~
    image:
      - NotBlank: ~
App\Entity\Variants\BookVariant:
  properties:
    isbnNumber:
      - NotNull: ~
      - Isbn:
          type: isbn13
          message: Ce champ doit être de type ISBN13
    format:
      - NotNull: ~
    parent:
      - NotNull: ~
App\Entity\Articles\Book\Book:
  properties:
    editor:
      - NotNull: ~
App\Entity\Formats\BookFormats:
  properties:
    name:
      - NotNull: ~
    
